### ISSUE TITLE
[Mint] Do not include the secret when returning a token is already spent error

### ISSUE THREAD

**Issue by callebtc** [cashubtc/nutshell#242]
Very tiny issue: The mint currently returns the secret of a token in the error message "Token already spent: <secret>".

This is pretty unnecessary.

**Comment by wfjvdham** [comment]
I have the idea this issue is solved already, since this is the custom error:

https://github.com/cashubtc/nutshell/blob/19de10bfea160b2cdb0e726d4ca1b0bf980df8b7/cashu/core/errors.py#L30-L35

**Comment by callebtc** [comment]
Awesome, thanks for this comment!
