### ISSUE TITLE
Add invoice memo and expiry to the request_mint method

### ISSUE THREAD

**Issue by minibits-cash** [cashubtc/nutshell#322]
It is not currently possible to pass but an amount to the mint request. If the invoice is about to be sent to third party and is not a "topup by myself" kind of transaction, setting memo and expiry can be important to the receiver of an invoice.

Current route:

`async def request_mint(amount: int = 0) -> GetMintResponse`

should accept and pass downstream memo: string and expiry: number and return accordingly formed invoice.

**Comment by findingsov** [comment]
This will help with this scenario in Minibits -async request for ecash:
Contact selet -> Request Ecash->Create Invoice->Send Request

**Comment by callebtc** [comment]
This has to be a change in the protocol [NUTs](https://github.com/cashubtc/nuts/). Please open an issue there so we can discuss this and add a memo field in `PostBolt11MintQuoteRequest`.

**Comment by minibits-cash** [comment]
PR proposal for optional description field is in the making here:

https://github.com/minibits-cash/nuts/blob/request-desc/04.md

**Comment by simongltr** [comment]
Just letting you know that adding a description to the invoice is also important for me. In the context of a lightning address server + a company account rewarding users with eCash it's really hard to differentiate a mint operation from the user vs from myself. With a description added to the invoice it makes accounting much easier and the standard `bkpr-listaccountevents` command is enough.
