### ISSUE TITLE
[Wallet] do not get mint keys when daemon starts up 

### ISSUE THREAD

**Issue by callebtc** [cashubtc/nutshell#339]
When running `cashu -d` the wallet gets the mint keys upon startup. This is bad because we can't start the daemon in a state where it has no access to any mint yet. Instead, the keys should be fetched on demand, when the wallet does its first operation with the mint.

**Comment by Guilospanck** [comment]
Hey, I suppose this is should be already closed by [#318](https://github.com/cashubtc/nutshell/pull/318), right?
