### ISSUE TITLE
Unable to Spend from Mint Created in LNbits

### ISSUE THREAD

**Issue by acurious** [cashubtc/nutshell#454]
I am encountering issues while setting up a Cashu mint in LNbits. I am able to create the mint and add it to various applications like enuts, nutstash, and cashu.me. Topping up the mint using lightning invoice works fine; however, I am unable to send eCash from this mint within any application. I face difficulties in creating a cashu token.  enuts displays an error message: "'Ledger' object has no attribute 'keyset'". Cashu.me reports: "Network Error when attempting to fetch resources". Nutstash encounters an error: "Error when creating Token. Sendable Token could not be created".

**Comment by callebtc** [comment]
Can you reproduce this error?

Please post it here: https://github.com/lnbits/cashu
