### ISSUE TITLE
StrikeWallet -> StrikeUSDWallet & Unit 'sat' not supported

### ISSUE THREAD

**Issue by Kodylow** [cashubtc/nutshell#469]
Deployed a mint on Replit, ran into:

1. StrikeWallet in README has been renamed to StrikeUSDWallet in the code

2. StrikeUSDWallet doesn't respect WALLET_UNIT env var, if you set it to 'sat' it still forces USD

<img width="489" alt="image" src="https://github.com/cashubtc/nutshell/assets/74332828/747b25c9-fe45-4d41-bbac-176fc11d84a4">

**Comment by callebtc** [comment]
Fixed in https://github.com/cashubtc/nutshell/pull/455

**Comment by callebtc** [comment]
Thank you!

`WALLET_UNIT` is only for the wallet, the mint uses the units in the keysets it generates.
