### ISSUE TITLE
Older dependencies for Sqlalchemy? 

### ISSUE THREAD

**Issue by trbouma** [cashubtc/nutshell#497]
I am trying to install the fastapi ```sqlmodel``` package to my cashu project and I get the following error:

```bash
> poetry add sqlmodel             
Using version ^0.0.16 for sqlmodel

Updating dependencies
Resolving dependencies... (0.0s)

Because no versions of sqlmodel match >0.0.16,<0.0.17
 and sqlmodel (0.0.16) depends on SQLAlchemy (>=2.0.0,<2.1.0), sqlmodel (>=0.0.16,<0.0.17) requires SQLAlchemy (>=2.0.0,<2.1.0).
So, because cashu depends on both SQLAlchemy (^1.3.24) and sqlmodel (^0.0.16), version solving failed.
```

I am wondering if the SQLAlchemy dependencies could be updated in the project so I can take advantage of sqlmodel. I will start investigating myself, but I thoought I would raise this an issue if there is an easy fix.

**Comment by trbouma** [comment]
It looks like the later version of SQLAlchemy has the aync support required which is now being provided by ```sqlalchemy_aio```. It's this library that is the problem dependency that is forcing SQLAlchemy to an older version. I will investigate to see if I can replace.

**Comment by callebtc** [comment]
Opened a new issue to track this.
