### ISSUE TITLE
Add CORS headers

### ISSUE THREAD

**Issue by benthecarman** [cashubtc/nutshell#510]
Ran into some issues with mints not having CORS headers. Would be nice if that came by default instead of needing to harass the mint operators to add the header to their nginx server

**Comment by callebtc** [comment]
Hm. There is a FastAPI CORS middleware in the server that is supposed to work but apparently it doesn't. Thank you for the issue, will figure out what's wrong.

**Comment by callebtc** [comment]
From personal correspondence: _The cors issue we were having ended up not being cors and was something else_
