### ISSUE TITLE
v1  checkstate work or  i compute Y correct ? 

### ISSUE THREAD

**Issue by biluohc** [cashubtc/nutshell#527]
The api of v1 always returns UNSPENT

```
curl -X POST https://8333.space:3338/check -H 'Content-Type: application/json' -d '{
"proofs": [
    {
        "amount": 1,
        "id": "I2yN+iRYfkzT",
        "secret": "99232add6fb22269ee815bcec1af337b542311604c4dc9135d2e699ec61d356a",
        "C": "02d58da4f652382ec44a4a7f9b4524ce14f488c4eedfa9526602f50930bb12a725"
    },
    {
        "amount": 1,
        "id": "I2yN+iRYfkzT",
        "secret": "ef6e03533899d4af2517f74f428bdc2b1c765fe3308df93efbcea3ef21ec8374",
        "C": "022d0cbca25b5a228c3372db9863ef8b86db9929ece30b2f9bc04a0e572db7e069"
    },
    {
        "amount": 1,
        "id": "I2yN+iRYfkzT",
        "secret": "71caf09b67546c7bc7d0161ca5fa82d341cbce4caae94f90ea079f22f8e66043",
        "C": "036cda9ef35841638286e6d74ed0d449443aa20fb9d25c8d8ab1c4195dbf60c63a"
    }
]
}'
```
v0 got: `{"spendable":[false,false,false],"pending":[false,false,false]}``

```
curl -X POST https://8333.space:3338/v1/checkstate -H 'Content-Type: application/json' -d '
{
"Ys": [
    "0241478d0b6578432841f56da9f1f30ee5c6aee02f2dae310f74a977e46786cde4",
    "02ecdf320c321b284a08a00b6acf067ff347134a1a522b5b4a1ef5b248b333b45d",
    "02a23e004486a9dadd671188f438f88fff118ff748d507f6d3952c395fc60b96ed"
]
}'
```
v1 got: 
`{"states":[{"Y":"0241478d0b6578432841f56da9f1f30ee5c6aee02f2dae310f74a977e46786cde4","state":"UNSPENT","witness":null},{"Y":"02ecdf320c321b284a08a00b6acf067ff347134a1a522b5b4a1ef5b248b333b45d","state":"UNSPENT","witness":null},{"Y":"02a23e004486a9dadd671188f438f88fff118ff748d507f6d3952c395fc60b96ed","state":"UNSPENT","witness":null}]}`

**Comment by callebtc** [comment]
Hey there, thank you for the report. Seems like an important issue if it turns out to be true.

Have you tried to compute the `hash_to_curve` from these `secrets` to check if you get the correct `Y` or were you able to reproduce this when you run the mint yourself? You should be able to check this quite easily by using `FakeWallet`.

**Comment by biluohc** [comment]
Thanks, I found that I should use the hex string of the private key instead of its bytes to calculate Y
