### ISSUE TITLE
Redeem time limit with re-claim feature

### ISSUE THREAD

**Issue by pailakapo** [cashubtc/nutshell#534]
If I send a token and the user never redeems, then the money is "lost."

This is similar to a check.  Sometimes payroll (and other) checks have a "must redeem within 90 days" to mitigate this future accounting problem.

eCash tokens could also be treated like a check.   

In sending a token, you could be saying, "I am giving you these funds as long as you redeem them to the mint within TIME_LIMIT days."  (90 could be a default, for example, but editable.)

The tokens created to be sent (even P2PK) could be presented in the sender's wallet as PENDING during the TIME_LIMIT until redeemed.  After TIME_LIMIT, the sender could be presented with a RE-CLAIM token button.  After TIME_LIMIT and until redeemed, both sender and receiver could redeem.  (ie the sender isn't REQUIRED to redeem, and they aren't automatically revoked.)

If the sender redeems, he is just putting the cash back in his wallet.  So after the time limit it just becomes a race to redeem.

**Comment by callebtc** [comment]
You can use `cashu pending` to see the tokens you have sent to someone. Wallets do not forget the tokens they send, in case they never get redeemed.
