### ISSUE TITLE
[Feature request] Add support for `clnrest.py`

### ISSUE THREAD

**Issue by simongltr** [cashubtc/nutshell#552]
To my understanding [clnrest.py](https://docs.corelightning.org/docs/rest) is intended to replace [c-lightning-REST](https://github.com/Ride-The-Lightning/c-lightning-REST/tree/master). 

Adding support for this integrated plugin would simplify the installation process

**Comment by simongltr** [comment]
I just saw #519, it would be even better!

**Comment by callebtc** [comment]
Complete

**Comment by callebtc** [comment]
PR: https://github.com/cashubtc/nutshell/pull/551
