### ISSUE TITLE
[readme edit] pyenv issue in manual install of poetry

### ISSUE THREAD

**Issue by 0xg4tt0** [cashubtc/nutshell#554]
First time mint-runner, attempting first install of nutshell on Linux Mint 21.3 Cinnamon / 5.15.0-112-generic kernel

Following this step: https://github.com/cashubtc/nutshell?tab=readme-ov-file#manual-install-poetry

Was struggling to get 'pyenv init' to start - it throws this error when attempting the command:

``` Load pyenv automatically by appending
# the following to 
# ~/.bash_profile if it exists, otherwise ~/.profile (for login shells)
# and ~/.bashrc (for interactive shells) :

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Restart your shell for the changes to take effect.
```

Here is where I noticed that the nutshall installation instructions point to the mint hardware using .bashrc

Some linux systems (such as Mint) use .profile as well as .bashrc - as is the case of Linux Mint

Because of my setup the 'solution' thrown in the error does not fix the issue 

Solution proposal: Adding two additional steps added to the manual install steps within the code snippet called 'Poetry: Prerequisites' ([link](https://github.com/cashubtc/nutshell?tab=readme-ov-file#poetry-prerequisites))

```
# on ubuntu:
sudo apt install -y build-essential pkg-config libffi-dev libpq-dev zlib1g-dev libssl-dev python3-dev libsqlite3-dev ncurses-dev libbz2-dev libreadline-dev lzma-dev

# install python using pyenv
curl https://pyenv.run | bash

# add the commands to ~/.bashrc by running the following in your terminal
# if your system uses .profile or .bash_profile please see [pyenv documentation](https://github.com/pyenv/pyenv?tab=readme-ov-file#set-up-your-shell-environment-for-pyenv)
echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(pyenv init -)"' >> ~/.bashrc

# !! follow the instructions of pyenv init to setup pyenv !!
pyenv init

# restart your shell (or source your .rc file), then install python:
pyenv install 3.10.4

# install poetry
curl -sSL https://install.python-poetry.org | python3 -
echo export PATH=\"$HOME/.local/bin:$PATH\" >> ~/.bashrc
source ~/.bashrc
```

Ref: pyenv readme.md: [https://github.com/pyenv/pyenv?tab=readme-ov-file#set-up-your-shell-environment-for-pyenv](https://github.com/pyenv/pyenv?tab=readme-ov-file#set-up-your-shell-environment-for-pyenv)

**Comment by callebtc** [comment]
Thank you for sharing your solution. Closing the issue since your issue seems fixed.
