### ISSUE TITLE
[wallet] Witness should be null not an empty string

### ISSUE THREAD

**Issue by thesimplekid** [cashubtc/nutshell#559]
If a witness is not required on the proof it should be null not an empty string. This is causing deserialization to fail in CDK. 
![image](https://github.com/cashubtc/nutshell/assets/8606367/63aa85e2-37ca-472a-83e5-691a81ab8df5)

https://github.com/cashubtc/nutshell/blob/75987beaf19897175f2be98151cb3c8cfba839ce/cashu/core/base.py#L109

**Comment by callebtc** [comment]
Thanks for noticinf.
