### ISSUE TITLE
Bug: Wallet should sanitize mint URLs

### ISSUE THREAD

**Issue by callebtc** [cashubtc/nutshell#603]
Wallet addas mint URLs with trailing `/` if they are added manually. The URL should be sanitized before treading it as a mint URL. 

NUT reference: https://github.com/cashubtc/nuts/pull/151

**Comment by sansosti** [comment]
Is this still open? Or has it been solved by https://github.com/cashubtc/nutshell/pull/605/ ?

**Comment by prusnak** [comment]
better fix in https://github.com/cashubtc/nutshell/pull/606 still pending
