### ISSUE TITLE
'cashu receive' results in creating database directory

### ISSUE THREAD

**Issue by wrapnuts** [cashubtc/nutshell#615]
### environment
   * ubuntu 22.04.4 LTS
   * pip in ./cashu_venv/lib/python3.10/site-packages (24.2)
   *  cashu Version: 0.16.0
### issue 
after upgrading to v16, nutshell makes new wallet called no_name when i send and then receive the same cashu again.
 
`(cashu_venv) tester@vBox:~$ cashu receive cashuAey... 
| INFO     | cashu.core.db:__init__:119 - Creating database directory: /home/tester/.cashu/no_name`

If i repeat the above process until my wallet is empty, then:
`cashu_venv) tester@vBox:~$ cashu balance
Balance: 0 sat `

However, I can restore my balance with: 
`(cashu_venv) tester@vBox:~$ mv .cashu/no_name/wallet.sqlite3 .cashu/wallet/wallet.sqlite`

Apart from this, nutshell does not make v4 cashu by default, it can however receive them from a [cashu.me](https.cashu.me) wallet

### final thoughts

i've tried updating sqlalchemy and broke nutshell, after that i saw #501 and reinstalled nutshell. Although i freshly installed nutshell v16 in a new vm, i still encountered the above issue. Pls let me know if there is anything else that i can try or provide you to help resolve this nutty issue. Keep nutting

**Comment by callebtc** [comment]
Thank you for submitting the issue. Could you check your `~/cashu/.env` file whether `WALLET_NAME` is set to some other value? The CLI should default to the wallet called "wallet" and not "no_name". 

Can you see your original wallet if you enter `cashu -w wallet info`? The `-w` flag lets you select the wallet.

If you could provide a step by step description of how nutshell creates a `no_name` wallet, it would be great for debugging.

Concerning V4: This token format is not supported with all keysets, some old proofs might still be serialized as v3. But the default is set to V4. You'll encounter more V4 in the future.
