### ISSUE TITLE
Add MINT_MAX_BALANCE_ISSUED setting

### ISSUE THREAD

**Issue by minibits-cash** [cashubtc/nutshell#646]
MINT_MAX_BALANCE_ISSUED would serve the purposes, when the mint operator wants to make sure the mint can not issue more units of ecash than the configured value.

This can serve multiple purposes - as a security limit as well as an imposed limit in case the unit issued is backed by a derivative position at the exchange that is pre-funded - i.e. fully hedged against exchange rate changes to bitcoin upfront it is available to be issued as ecash.

**Comment by lollerfirst** [comment]
I wonder if this is information we should display in a `GET /v1/info` request.
If so, we should probably do a NUT about it.

**Comment by minibits-cash** [comment]
Agree, but I think it's not a prerequisite for implementation. From user pov max one time mint / melt limits that are already there are more important then a total.

**Comment by lollerfirst** [comment]
@minibits-cash There's two ways I would do this:
1) When generating a mint quote, sneak in a balance request to the backend right before requesting the invoice.
    If balance >= MINT_MAX_BALANCE_ISSUED then abort
2) Add a table to the DB that keeps track of the amounts worth of issued ecash for each unit, then for every mint quote
    request check that the balance for the particular unit is not exceeded.

**Comment by minibits-cash** [comment]
I think it's fully upon mint to enforce it and just fail thebfirat mint request hitting the limit.

**Comment by lollerfirst** [comment]
Yes. I was referring to how I would implement this here in Nutshell.

https://github.com/cashubtc/nutshell/commit/bff30d493d72d123e8963476901b431bd8de1383#diff-563ab1fc2a5b2676a9794be3b08bb863afc36b495cbe4653ced3fdeb430bf530R252-R256

Looks like there already is a check of the first type I mentioned. Although it doesn't seem to account for different units.

**Comment by minibits-cash** [comment]
> Yes. I was referring to how I would implement this here in Nutshell.
> 
> [bff30d4#diff-563ab1fc2a5b2676a9794be3b08bb863afc36b495cbe4653ced3fdeb430bf530R252-R256](https://github.com/cashubtc/nutshell/commit/bff30d493d72d123e8963476901b431bd8de1383#diff-563ab1fc2a5b2676a9794be3b08bb863afc36b495cbe4653ced3fdeb430bf530R252-R256)
> 
> Looks like there already is a check of the first type I mentioned. Although it doesn't seem to account for different units.

Ah sorry, I misunderstood that.

Ad balance check: I believe nutshell already uses database views to calculate overall minted and melted amounts as well as issued balance. 

Not sure how it handles the units tho.
I remind calle mentioning that max mint and melt configs do not handle units currentky

**Comment by minibits-cash** [comment]
I now found that there already is MINT_MAX_BALANCE existing setting doing the same, so I close this one.

**Comment by minibits-cash** [comment]
Related PR #652 could then focus to extend existing limits so they support multiple units (as they would likely be incorrectly applied as of now):

# Limits
# Max mint balance in satoshis
# MINT_MAX_BALANCE=1000000
# Max peg-in amount in satoshis
# MINT_MAX_PEG_IN=100000
# Max peg-out amount in satoshis
# MINT_MAX_PEG_OUT=100000

**Comment by minibits-cash** [comment]
There is now separate issue for this extended scope: #650
